["What?",
"Does that work?",
"That didn’t work.",
"Really!?",
"At the end of the day…",
"That’s ridiculous!",
"Ruby/Rails is awesome.",
"Whomp whomp.",
"Tada!",
"_____ is making my head explode",
"Any questions?",
"Stupid programmers.",
"Good job!",
"This is so cool!",
"Avi dismisses a question",
"Avi forgets to turn on join.me/record.",
"Avi’s hipchat window pops up",
"Avi Curses",
"Avi asks Logan a question",
"Does that work?",
"That didn’t work.",
"Really!?",
"At the end of the day…",
"That’s ridiculous!"]
